### ISSUE TITLE
Missing Galaxy wheels

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/starforge-recipes#26]
In **bold** the packages containing compiled extensions, which cannot be installed (or fully installed) without a compiler and Python development libraries.

- [x] bagit: wheel missing for all Python versions, https://github.com/LibraryOfCongress/bagit-python/pull/109, https://github.com/LibraryOfCongress/bagit-python/issues/116 https://github.com/galaxyproject/starforge-recipes/pull/72
- [x] bdbag: https://github.com/galaxyproject/galaxy/pull/6324
- [ ] beaker: wheel missing for all Python versions
- [x] bunch: wheel missing for all Python versions, unmaintained, dropped in https://github.com/CloudVE/cloudbridge/pull/171 and https://github.com/galaxyproject/galaxy/pull/7546
- [x] **bx-python**: https://github.com/galaxyproject/starforge-recipes/pull/13
- [x] cachecontrol: wheel available since 0.12.6
- [x] cheetah3: wheel missing for OSX, will be available starting with 3.2.1 https://github.com/CheetahTemplate3/cheetah3/issues/4 https://github.com/CheetahTemplate3/cheetah3/issues/11 https://github.com/CheetahTemplate3/cheetah3/pull/14
- [x] cliff: https://bugs.launchpad.net/python-cliff/+bug/1760157 https://review.openstack.org/#/c/574846/ https://github.com/galaxyproject/galaxy/pull/6469
- [x] cloudbridge: https://github.com/gvlproject/cloudbridge/pull/118 https://github.com/galaxyproject/starforge-recipes/pull/18
- [x] deprecation: https://github.com/briancurtin/deprecation/pull/33 https://github.com/galaxyproject/galaxy/pull/6921
- [ ] dictobj: wheel missing for all Python versions
- [ ] dogpile.cache: wheel missing for all Python versions, has support for universal wheels, https://github.com/sqlalchemy/dogpile.cache/issues/126
- [ ] fabric3: wheel missing for Python 2.7, https://github.com/mathiasertl/fabric/pull/49
- [x] future: wheel missing for all Python versions, https://github.com/PythonCharmers/python-future/issues/411 https://github.com/PythonCharmers/python-future/pull/536
- [ ] google-api-python-client: wheel missing for Python 2, could be made universal https://github.com/googleapis/google-api-python-client/pull/948
- [x] mako: wheel missing for all Python versions, https://github.com/sqlalchemy/mako/pull/314
- [x] **markupsafe**: https://github.com/pallets/markupsafe/issues/45 https://github.com/galaxyproject/starforge-recipes/pull/24
- [x] **mercurial**: https://github.com/galaxyproject/starforge-recipes/pull/57
- [x] msgpack: OSX wheels available for 1.0.0 and cp36-cp38 https://github.com/msgpack/msgpack-python/pull/409
- [x] munch: https://github.com/Infinidat/munch/pull/33
- [x] netifaces: https://github.com/galaxyproject/galaxy/pull/6324
- [x] nodeenv: wheel available since 1.3.4
- [x] os-service-types: wheel missing for Python 2.7
- [x] osc-lib: wheel missing for Python 2.7
- [ ] prettytable: wheel missing for all Python versions, unmaintained
- [x] **psutil**: https://github.com/giampaolo/psutil/issues/1550#issuecomment-748401967 https://github.com/galaxyproject/starforge-recipes/pull/17
- [x] pycparser: universal wheel missing, https://github.com/eliben/pycparser/issues/288 https://github.com/eliben/pycparser/issues/359
- [x] pycrypto: https://github.com/galaxyproject/galaxy/pull/6324
- [ ] pyinotify: unmaintained, wheel missing for all Python versions, https://github.com/seb-m/pyinotify/issues/111
- [ ] pyperclip: wheel missing for all Python versions, https://github.com/asweigart/pyperclip/pull/131
- [ ] **pyrsistent**: wheel missing for all Python versions, https://github.com/tobgu/pyrsistent/issues/88 https://github.com/tobgu/pyrsistent/pull/170 https://github.com/tobgu/pyrsistent/issues/196
- [x] **pysam**: wheel missing for OSX, https://github.com/pysam-developers/pysam/issues/722 https://github.com/galaxyproject/starforge-recipes/pull/32
- [ ] pysftp: wheel missing for all Python versions
- [x] python-ldap: wheel missing for all Python versions, https://github.com/python-ldap/python-ldap/issues/191 https://github.com/galaxyproject/starforge-recipes/pull/46
- [x] **python-lzo**: https://github.com/galaxyproject/starforge-recipes/pull/3
- [x] **pyyaml**: https://github.com/yaml/pyyaml/issues/43 https://github.com/yaml/pyyaml/pull/407 https://github.com/galaxyproject/starforge-recipes/pull/19
- [ ] rdflib: wheel missing for Python 2.7, could be made universal
- [ ] rdflib-jsonld: wheel missing for all Python versions
- [ ] repoze.lru: wheel missing for Python 2.7, https://github.com/repoze/repoze.lru/pull/29
- [ ] scandir: wheel available only for Windows
- [ ] simplejson: wheel missing for Linux, https://github.com/simplejson/simplejson/issues/181
- [x] sqlalchemy: wheel missing for all Python versions https://github.com/sqlalchemy/sqlalchemy/pull/5241
- [x] sqlalchemy-migrate: https://review.openstack.org/#/c/577002/
- [ ] sqlalchemy-utils: wheel missing for all Python versions https://github.com/kvesteri/sqlalchemy-utils/pull/312
- [x] **subprocess32**: wheel missing on Linux, https://github.com/google/python-subprocess32/issues/60 https://github.com/galaxyproject/starforge-recipes/pull/14
- [ ] tempita: wheel missing for all Python versions
- [x] tzlocal: wheel missing for all Python versions https://github.com/regebro/tzlocal/issues/63
- [x] ubiquerg: could be made universal https://github.com/pepkit/ubiquerg/pull/29
- [x] **uwsgi**: wheel missing for Python 3, https://github.com/unbit/uwsgi/issues/816
- [ ] warlock: wheel missing for all Python versions
- [x] **watchdog**: https://github.com/gorakhargosh/watchdog/issues/428 https://github.com/galaxyproject/starforge-recipes/pull/21 https://github.com/gorakhargosh/watchdog/pull/739
- [x] **wrapt**: wheel missing for all Python versions, https://github.com/GrahamDumpleton/wrapt/issues/39 https://github.com/GrahamDumpleton/wrapt/pull/105 https://github.com/galaxyproject/starforge-recipes/pull/25

**Comment by davidism** [comment]
Saw this linked in the MarkupSafe issue tracker. MarkupSafe 1.1.0 has wheels on PyPI now, not sure if that affects this project.

**Comment by nsoranzo** [comment]
@davidism Thanks for the heads-up! No need to build our own wheels any more!

**Comment by demianzhang** [comment]
windows pip install future will meet this error
Relative imports in setup.py would make execution of it complain with modules `src.future` not being found.

```
/some/different/path/python setup.py install
```
Error:

```
import src.future
ModuleNotFoundError: No module named 'src'
```
Could you fix it soon?

pip 19.0.3
python 3.6.4
windows

**Comment by nsoranzo** [comment]
@demianzhang We are not supporting Windows at this moment, patches welcome though!

**Comment by demianzhang** [comment]
Thanks for your reply. I find the reason to this error is that windows python can not find the local file src. When I insert the path in setup.py using sys.path.append(). Everything goes right. I do not know the reason why the python can not import the local path directly in Windows.

**Comment by demianzhang** [comment]
I find that sys.path.append('') will be OK. Thx
